version : '3'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: msgSenderMicroservice
      POSTGRES_HOST: 8080
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgressql/data
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - "8097:8080"
    depends_on:
      - postgres
volumes:
  postgres-data:
