version: '3'

services:
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres

  rabbitmq:
    image: "rabbitmq:management"
    container_name: my_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  adminer:
    image: adminer
    container_name: my_adminer
    ports:
      - "8082:8080"

volumes:
  postgres_data:
